changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - dependabot
  categories:
    - title: Added
      labels:
        - enhancement
        - feature
    - title: Fixed
      labels:
        - bug
        - fix
    - title: Security
      labels:
        - security
    - title: Documentation
      labels:
        - documentation
    - title: Other Changes
      labels:
        - "*"
